[package]
name = "vitr"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
minijinja = { version = "2.15.1", features = ["loader"] }
minijinja-autoreload = "2.15.1"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.13.1"
